DELIMITER $$
CREATE TRIGGER zaMalo
BEFORE INSERT ON Platnosci
FOR EACH ROW
BEGIN
IF NEW.kwota < 500 THEN
SET NEW.kwota = 0;
END IF;
END
$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER zaKrotkie
BEFORE INSERT ON Uczniowie
FOR EACH ROW
BEGIN
IF LENGTH(new.nazwisko) < 3 THEN
SET NEW.nazwisko = NULL;
END IF;
END
$$
DELIMITER ;